package fr.nexa.dailyorg_java.controller.dailyorg;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Logger;

import org.springframework.http.ResponseEntity;
import org.springframework.lang.NonNull;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import fr.nexa.dailyorg_java.config.JwtUtil;
import fr.nexa.dailyorg_java.model.AppUser;
import fr.nexa.dailyorg_java.model.dailyorg.OrganizerUser;
import fr.nexa.dailyorg_java.model.dailyorg.RecurringTaskState;
import fr.nexa.dailyorg_java.model.dailyorg.Task;
import fr.nexa.dailyorg_java.model.dailyorg.TaskPriority;
import fr.nexa.dailyorg_java.service.AppUserService;
import fr.nexa.dailyorg_java.service.dailyorg.impl.OrganizerUserService;
import fr.nexa.dailyorg_java.service.dailyorg.impl.RecurringTaskStateService;
import fr.nexa.dailyorg_java.service.dailyorg.impl.TaskPriorityService;
import fr.nexa.dailyorg_java.service.dailyorg.impl.TaskService;
import jakarta.servlet.http.HttpServletRequest;
import lombok.AllArgsConstructor;

@RestController
@RequestMapping("/api/task")
@AllArgsConstructor
public class TaskController {

	private final JwtUtil jwtUtil;

	private final TaskService taskService;
	private final RecurringTaskStateService recurringTaskStateService;
	private final AppUserService appUserService;
	private final OrganizerUserService organizerUserService;
	private final TaskPriorityService taskPriorityService;

	private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

	@PutMapping("/create_task")
	public ResponseEntity<?> createTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("task_name") || !data.containsKey("task_required_energy") || !data.containsKey("task_start_date") || !data.containsKey("task_end_date") || !data.containsKey("task_priority")) {
				return ResponseEntity.badRequest().body("One or multiple mandatory fields are missing...");
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			RecurringTaskState state = null;

			// Validate task priority if exists
			Optional<TaskPriority> taskPriority = taskPriorityService.getTaskPriorityByTaskPriorityName(data.get("task_priority"));
			if (!taskPriority.isPresent()) {
				return ResponseEntity.badRequest().body("Task priority not found...");
			}

			// Check and initialize the recurring task state if needed
			boolean isRecurrent = data.containsKey("is_recurrent") ? Boolean.parseBoolean(data.get("is_recurrent")) : false;

			if (isRecurrent && data.containsKey("task_repeat_frequency") && data.containsKey("task_repeat_end_date")) {
				long repeatFrequencyID = Long.parseLong(data.get("task_repeat_frequency"));
				Optional<RecurringTaskState> recurringTaskState = recurringTaskStateService.findById(repeatFrequencyID);

				if (recurringTaskState.isPresent()) {
					state = recurringTaskState.get();
				} else {
					return ResponseEntity.badRequest().body("Recurring task state not found...");
				}
			}

			Task task = Task.builder().taskName(data.get("task_name")).ocurrenceUniqueId(UUID.randomUUID().toString()).taskRequiredEnergy(Integer.parseInt(data.get("task_required_energy"))).taskStartDate(LocalDateTime.parse(data.get("task_start_date"))).taskEndDate(LocalDateTime.parse(data.get("task_end_date"))).taskPriority(taskPriority.get())
					.taskDescription(data.containsKey("task_description") ? data.get("task_description") : "Empty").taskAutoGenerated(false).recurringTaskState(isRecurrent ? state : null).recurrenceEndDate(isRecurrent ? LocalDate.parse(data.get("task_repeat_end_date"), formatter).atStartOfDay() : null).build();

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				// Check if the user already have an organizer profile
				// If not, create one
				AppUser appUser = user.get();
				boolean hasBeenCreated = checkProfile(appUser);

				task.setOrganizerUser(appUser.getOrganizerUser());
				taskService.addTask(task);

				return ResponseEntity.ok(hasBeenCreated ? "Task and profile created..." : "Task created...");
			} else {
				return ResponseEntity.badRequest().body("User not found...");
			}

		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe("Invalid number format for task_required_energy: " + e.getMessage());
			return ResponseEntity.badRequest().body("Invalid number format for task_required_energy...");
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe("Internal error: " + e.getMessage());
			return ResponseEntity.internalServerError().body("Internal error...");
		}
	}

	@PutMapping("/update_task")
	public ResponseEntity<?> updateTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("task_id") || !data.containsKey("task_name") || !data.containsKey("task_required_energy") || !data.containsKey("task_start_date") || !data.containsKey("task_end_date")) {
				return ResponseEntity.badRequest().body("One or multiple mandatory fields are missing...");
			}

			for (String key : data.keySet()) {
				System.err.println("Key: " + key + ", Value: " + data.get(key));
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				Task task = taskService.getTaskById(Long.parseLong(data.get("task_id")));

				// Check and initialize the recurring task state if needed
				boolean isRecurrent = data.containsKey("is_recurrent") ? Boolean.parseBoolean(data.get("is_recurrent")) : false;

				if (task != null && task.getOrganizerUser().getAppUser().getUserId() == appUser.getUserId()) {
					task.setTaskName(data.get("task_name"));
					task.setTaskRequiredEnergy(Integer.parseInt(data.get("task_required_energy")));
					task.setTaskStartDate(LocalDateTime.parse(data.get("task_start_date")));
					task.setTaskEndDate(LocalDateTime.parse(data.get("task_end_date")));
					task.setTaskDescription(data.containsKey("task_description") ? data.get("task_description") : "Empty");
					task.setTaskPriority(taskPriorityService.getTaskPriorityByTaskPriorityName(data.get("task_priority")).orElse(null));

					if (!isRecurrent) {
						task.setRecurringTaskState(null); // If the task is not recurrent, set the recurring task state to null
						task.setRecurrenceEndDate(null); // Also set the recurrence end date to null
					} else {
						long repeatFrequencyID = Long.parseLong(data.get("task_repeat_frequency"));
						Optional<RecurringTaskState> recurringTaskState = recurringTaskStateService.findById(repeatFrequencyID);

						if (recurringTaskState.isPresent()) {
							RecurringTaskState state = recurringTaskState.get();
							task.setRecurringTaskState(state); // Set the new recurring task state
							task.setRecurrenceEndDate(LocalDate.parse(data.get("task_repeat_end_date"), formatter).atStartOfDay());
						}
					}

					if (data.containsKey("is_task_completed")) {
						boolean isCompleted = Boolean.parseBoolean(data.get("is_task_completed"));
						task.setTaskCompleted(isCompleted);
						task.setTaskCompletionDate(isCompleted ? LocalDateTime.now() : null);
					}
					
					taskService.updateTask(task);
					return ResponseEntity.ok().body("Task updated successfully...");
				} else {
					return ResponseEntity.badRequest().body("Task not found or does not belong to the user...");
				}
			} else {
				return ResponseEntity.badRequest().body("User not found...");
			}
		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe("Invalid number format for task_id or task_required_energy: " + e.getMessage());
			return ResponseEntity.badRequest().body("Invalid number format for task_required_energy...");
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe("Internal error: " + e.getMessage());
			return ResponseEntity.internalServerError().body("Internal error...");
		}
	}

	@DeleteMapping("/delete_task")
	public ResponseEntity<?> deleteTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("task_id")) {
				return ResponseEntity.badRequest().body("One or multiple mandatory fields are missing...");
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				Task task = taskService.getTaskById(Long.parseLong(data.get("task_id")));

				if (task != null && task.getOrganizerUser().getAppUser().getUserId() == appUser.getUserId()) {
					taskService.deleteTask(task);
					return ResponseEntity.ok().body("Task deleted successfully...");
				} else {
					return ResponseEntity.badRequest().body("Task not found or does not belong to the user...");
				}
			} else {
				return ResponseEntity.badRequest().body("User not found...");
			}
		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe("Invalid number format for task_id: " + e.getMessage());
			return ResponseEntity.badRequest().body("Invalid number format for task_id...");
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe("Internal error: " + e.getMessage());
			return ResponseEntity.internalServerError().body("Internal error...");
		}
	}

	@PostMapping("/get_tasks_by_date")
	public ResponseEntity<?> getTasksByDate(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("date")) {
				return ResponseEntity.badRequest().body("One or multiple mandatory fields are missing...");
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				OrganizerUser organizerUser = organizerUserService.findByAppUserId(appUser);
				return ResponseEntity.ok(taskService.getAllTasksByUserIdAndDate(organizerUser, LocalDateTime.parse(data.get("date"))));
			} else {
				return ResponseEntity.badRequest().body("User not found...");
			}
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe("Internal error: " + e.getMessage());
			return ResponseEntity.internalServerError().body("Internal error...");
		}
	}

	@GetMapping("/get_all_tasks_recurring_states")
	public ResponseEntity<?> getAllRecurringTaskStates() {
		try {
			List<RecurringTaskState> recurringTaskStates = recurringTaskStateService.findAll();
			List<HashMap<String, String>> response = new ArrayList<>();

			for (RecurringTaskState recurringTaskState : recurringTaskStates) {
				HashMap<String, String> map = new HashMap<>();
				map.put("id", String.valueOf(recurringTaskState.getRecurringTaskStateId()));
				map.put("display_name", "Every " + (recurringTaskState.getTimeInterval() > 1 ? recurringTaskState.getTimeInterval() + " " : " ") + RecurringTaskState.RecurringTaskFrequency.fromValue(recurringTaskState.getFrequency()).getLabel());
				response.add(map);
			}

			return ResponseEntity.ok(response);
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe("Internal error: " + e.getMessage());
			return ResponseEntity.internalServerError().body("Internal error...");
		}
	}

	@PostMapping("/get_tasks_between_dates")
	public ResponseEntity<?> getTasksBetweenDates(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("start_date") || !data.containsKey("end_date")) {
				return ResponseEntity.badRequest().body("One or multiple mandatory fields are missing...");
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());

			System.err.println("User email extracted from cookies: " + userEmail);

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				// OrganizerUser organizerUser = organizerUserService.findByAppUserId(appUser);
				List<Task> tasks = taskService.getAllTasksByUserIdAndDateRange(appUser.getOrganizerUser(), LocalDateTime.parse(data.get("start_date")), LocalDateTime.parse(data.get("end_date")));

				return ResponseEntity.ok(tasks);
			} else {
				return ResponseEntity.badRequest().body("User not found...");
			}
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe("Internal error: " + e.getMessage());
			return ResponseEntity.internalServerError().body("Internal error...");
		}
	}

	/**
	 * Check if the user already have an organizer profile if not, create one
	 * 
	 * @param appUser
	 * @throws Exception
	 */
	private boolean checkProfile(AppUser appUser) throws Exception {
		if (appUser.getOrganizerUser() == null) {
			// Create an organizer profile for the user TODO change that later if needed
			OrganizerUser organizerUser = OrganizerUser.builder().appUser(appUser).calendarFirstShownHour(0).calendarTotalShownHours(24).build();
			appUser.setOrganizerUser(organizerUser);
			organizerUserService.create(organizerUser);
			appUserService.updateUser(appUser);
			Logger.getLogger(TaskController.class.getName()).info("Organizer profile created for user: " + appUser.getEmail());
			return true;
		}

		return false;
	}

}
