package fr.nexa.dailyorg_java.model.dailyorg;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Builder;
import lombok.Data;

@Entity
@Builder
@Data
@Table(name = "TaskOccurence")
public class TaskOccurence {

	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
	private long taskOccurenceId;
	
	@Column(nullable = false)
	private boolean isAutoGenerated;
	
	@Column(nullable = false)	
	private LocalDateTime taskOccurenceDate;
	
	@Column(nullable = true)
	private String userNotes;
	
	@ManyToOne
	@JoinColumn(name = "taskOccurences")
	private Task taskId;
	
	@ManyToOne
	@JoinColumn(name = "taskStatus")
	private TaskStatus taskStatus;
}
