package fr.nexa.dailyorg.model.dailyorg;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Builder
@Getter @Setter @AllArgsConstructor @NoArgsConstructor
@Table(name = "Task")
public class Task {
	
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	
	@Column(nullable = false, length = 50)
	private String taskName;
	
	@Column(length = 255)
	private String taskDescription;
	
	@Column(nullable = false)
	private LocalDateTime taskCreationDate;
	
	@Column()
	private LocalDateTime taskCompletionDate;
	
	@Column(nullable = false)
	private int taskRequiredEnergy;
	
	@Column(nullable = false)
	private LocalDateTime taskStartDate;
	
	@Column(nullable = false)
	private boolean isTaskCompleted;
	
	@Column(nullable = false)
	private LocalDateTime taskEndDate;
	
	@Column(nullable = false)
	@JsonIgnore
	private boolean taskAutoGenerated;
	
	@Column(nullable = true)
	private LocalDateTime recurrenceEndDate;
	
	@Column(nullable = false, length = 64, name = "ocurrenceUniqueId")
	private String ocurrenceUniqueId;

	@PrePersist
	public void prePersist() {
		this.taskCreationDate = LocalDateTime.now();
		this.isTaskCompleted = false;
	}
	
	@ManyToOne
	@JoinColumn(name = "organizer_user")
	@JsonIgnore
	private OrganizerUser organizerUser;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "task_priority")
	private TaskPriority taskPriority;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "recurring_task_state")
	private RecurringTaskState recurringTaskState;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category")
	private Category category;
}
