package fr.nexa.dailyorg_java.components.dailyorg;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

import fr.nexa.dailyorg_java.components.dailyorg.event.TaskChangedEvent;
import fr.nexa.dailyorg_java.model.dailyorg.RecurringTaskState;
import fr.nexa.dailyorg_java.model.dailyorg.Task;
import fr.nexa.dailyorg_java.service.dailyorg.impl.RecurringTaskStateService;
import fr.nexa.dailyorg_java.service.dailyorg.impl.TaskService;
import lombok.AllArgsConstructor;

// This component is responsible to create any task occurrences
// When a change is made in the database (task table), this component will update the occurrences...
@Component
@AllArgsConstructor
public class TaskOccurengeEngine {

	private final RecurringTaskStateService recurringTaskStateService;
	private final TaskService taskService;

	@SuppressWarnings("null")
	@EventListener
	public void handleTaskChangedEvent(TaskChangedEvent event) {
		// Handle the task change event
		// This method will be called when a task is created, updated or deleted
		String uuid = UUID.randomUUID().toString();

		List<Task> tasksToDelete = new ArrayList<>();

		Task task = taskService.getTaskById(event.getTaskId());
		if (task == null && event.getChangeType() != TaskChangedEvent.TaskChangeType.DELETED) {
			throw new IllegalArgumentException("Task with ID " + event.getTaskId() + " does not exist.");
		}

		switch (event.getChangeType()) {
		case CREATED:
			// Create task occurrences based on the master task
			// First, check if the task is a recurring task

			if (task.isTaskAutoGenerated()) {
				return;
			}

			if (task.getRecurringTaskState() != null) {
				createRecurringTaskOccurrences(task, task.getOcurrenceUniqueId());
			}

			break;

		case UPDATED:
			List<Task> tasksToUpdate = taskService.getAllTasksByOcurrenceUniqueId(task.getOcurrenceUniqueId());

			if (event.isRecurringTaskStateChanged()) {
				tasksToDelete = tasksToUpdate.stream().filter(t -> t.getId() != task.getId()).toList();
				taskService.deleteAllTasks(tasksToDelete, false); // Delete all occurrences except the master task

				if (task.getRecurringTaskState() == null) {
					return;
				} else {
					createRecurringTaskOccurrences(task, task.getOcurrenceUniqueId());
				}
			}

			for (Task t : tasksToUpdate) {
				t.setTaskName(task.getTaskName());
				t.setTaskDescription(task.getTaskDescription());
				t.setTaskRequiredEnergy(task.getTaskRequiredEnergy());

				// Only set the hours and minutes - NOT the date
				t.setTaskStartDate(LocalDateTime.of(t.getTaskStartDate().toLocalDate(), task.getTaskStartDate().toLocalTime()));
				t.setTaskEndDate(LocalDateTime.of(t.getTaskEndDate().toLocalDate(), task.getTaskEndDate().toLocalTime()));

				t.setTaskPriority(task.getTaskPriority());
				t.setRecurringTaskState(task.getRecurringTaskState());

				taskService.updateTask(t, false); // Update each occurrence of the task
			}

			break;

		case DELETED:
			tasksToDelete = taskService.getAllTasksByOcurrenceUniqueId(task.getOcurrenceUniqueId());
			if (!tasksToDelete.isEmpty()) {
				taskService.deleteAllTasks(tasksToDelete, false); // Delete all occurrences of the task
			}

			break;

		default:
			throw new IllegalArgumentException("Unknown task change type: " + event.getChangeType());
		}
	}

	private void createRecurringTaskOccurrences(Task task, String uuid) {
		// Logic to create task occurrences based on the recurring task state
		// This method should handle the logic to create occurrences based on the
		// frequency and time interval
		List<Long> affectedTasks = new ArrayList<>();
		affectedTasks.add(task.getId());

		LocalDateTime computedStartDate = task.getTaskStartDate();
		LocalDateTime computedEndDate = task.getTaskEndDate();

		RecurringTaskState recurringTaskState = recurringTaskStateService.findById(task.getRecurringTaskState().getRecurringTaskStateId()).orElseThrow(() -> new IllegalArgumentException("Recurring task state with ID " + task.getRecurringTaskState().getRecurringTaskStateId() + " does not exist."));

		while (computedEndDate.isBefore(task.getRecurrenceEndDate())) {
			// Increment the start and end dates based on the recurrence frequency
			if (recurringTaskState.getFrequency() == RecurringTaskState.RecurringTaskFrequency.WEEKLY.getValue()) {
				computedStartDate = computedStartDate.plusWeeks(recurringTaskState.getTimeInterval());
				computedEndDate = computedEndDate.plusWeeks(recurringTaskState.getTimeInterval());
			} else if (recurringTaskState.getFrequency() == RecurringTaskState.RecurringTaskFrequency.MONTHLY.getValue()) {
				computedStartDate = computedStartDate.plusMonths(recurringTaskState.getTimeInterval());
				computedEndDate = computedEndDate.plusMonths(recurringTaskState.getTimeInterval());
			} else if (recurringTaskState.getFrequency() == RecurringTaskState.RecurringTaskFrequency.DAILY.getValue()) {
				computedStartDate = computedStartDate.plusDays(recurringTaskState.getTimeInterval());
				computedEndDate = computedEndDate.plusDays(recurringTaskState.getTimeInterval());
			} else {
				throw new IllegalArgumentException("Unknown recurrence frequency: " + recurringTaskState.getFrequency());
			}

			if (computedEndDate.toLocalDate().atStartOfDay().isAfter(task.getRecurrenceEndDate().toLocalDate().atStartOfDay())) {
				break;
			}

			Task createdTask = Task.builder().taskName(task.getTaskName()).taskDescription(task.getTaskDescription()).taskCreationDate(LocalDateTime.now()).taskCompletionDate(null) // No completion date for new
																																														// occurrences
					.taskRequiredEnergy(task.getTaskRequiredEnergy())
					.taskStartDate(computedStartDate)
					.isTaskCompleted(false) // New occurrences are not completed
					.taskEndDate(computedEndDate)
					.organizerUser(task.getOrganizerUser())
					.taskPriority(task.getTaskPriority())
					.recurringTaskState(recurringTaskState)
					.taskAutoGenerated(true)
					.recurrenceEndDate(task.getRecurrenceEndDate()) // Set the recurrence end date
					.ocurrenceUniqueId(uuid) // Set the unique ID for the occurrence
					.build();

			taskService.addTask(createdTask);
		}
	}
}