package fr.nexa.dailyorg.controller.dailyorg;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Logger;

import org.springframework.http.ResponseEntity;
import org.springframework.lang.NonNull;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import fr.nexa.dailyorg.config.JwtUtil;
import fr.nexa.dailyorg.model.AppUser;
import fr.nexa.dailyorg.model.dailyorg.OrganizerUser;
import fr.nexa.dailyorg.model.dailyorg.RecurringTaskState;
import fr.nexa.dailyorg.model.dailyorg.Task;
import fr.nexa.dailyorg.model.dailyorg.TaskPriority;
import fr.nexa.dailyorg.service.AppUserService;
import fr.nexa.dailyorg.service.dailyorg.impl.OrganizerUserService;
import fr.nexa.dailyorg.service.dailyorg.impl.RecurringTaskStateService;
import fr.nexa.dailyorg.service.dailyorg.impl.TaskPriorityService;
import fr.nexa.dailyorg.service.dailyorg.impl.TaskService;
import fr.nexa.dailyorg.utils.EErrorMessages;
import jakarta.servlet.http.HttpServletRequest;
import lombok.AllArgsConstructor;

@RestController
@RequestMapping("/api/task")
@AllArgsConstructor
public class TaskController {

	private final JwtUtil jwtUtil;

	private final TaskService taskService;
	private final RecurringTaskStateService recurringTaskStateService;
	private final AppUserService appUserService;
	private final OrganizerUserService organizerUserService;
	private final TaskPriorityService taskPriorityService;

	private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

	@PutMapping("/create_task")
	public ResponseEntity<?> createTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey(ETaskControllerFields.TASK_NAME.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_REQUIRED_ENERGY.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_START_DATE.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_END_DATE.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_PRIORITY.getFieldName())) {
				return ResponseEntity.badRequest().body("One or multiple mandatory fields are missing...");
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			RecurringTaskState state = null;

			// Validate task priority if exists
			Optional<TaskPriority> taskPriority = taskPriorityService.getTaskPriorityByTaskPriorityName(data.get(ETaskControllerFields.TASK_PRIORITY.getFieldName()));
			if (!taskPriority.isPresent()) {
				return ResponseEntity.badRequest().body("Task priority not found...");
			}

			// Check and initialize the recurring task state if needed
			boolean isRecurrent = Boolean.parseBoolean(data.get(ETaskControllerFields.TASK_IS_RECURRENT.getFieldName()));

			if (isRecurrent && data.containsKey(ETaskControllerFields.TASK_REPEAT_FREQUENCY.getFieldName()) && data.containsKey(ETaskControllerFields.TASK_REPEAT_END_DATE.getFieldName())) {
				long repeatFrequencyID = Long.parseLong(data.get(ETaskControllerFields.TASK_REPEAT_FREQUENCY.getFieldName()));
				Optional<RecurringTaskState> recurringTaskState = recurringTaskStateService.findById(repeatFrequencyID);

				if (recurringTaskState.isPresent()) {
					state = recurringTaskState.get();
				} else {
					return ResponseEntity.badRequest().body("Recurring task state not found...");
				}
			}

			Task task = Task.builder().taskName(data.get(ETaskControllerFields.TASK_NAME.getFieldName())).ocurrenceUniqueId(UUID.randomUUID().toString()).taskRequiredEnergy(Integer.parseInt(data.get(ETaskControllerFields.TASK_REQUIRED_ENERGY.getFieldName()))).taskStartDate(LocalDateTime.parse(data.get(ETaskControllerFields.TASK_START_DATE.getFieldName()))).taskEndDate(LocalDateTime.parse(data.get(ETaskControllerFields.TASK_END_DATE.getFieldName()))).taskPriority(taskPriority.get())
					.taskDescription(data.containsKey(ETaskControllerFields.TASK_DESCRIPTION.getFieldName()) ? data.get(ETaskControllerFields.TASK_DESCRIPTION.getFieldName()) : "Empty").taskAutoGenerated(false).recurringTaskState(isRecurrent ? state : null).recurrenceEndDate(isRecurrent ? LocalDate.parse(data.get(ETaskControllerFields.TASK_REPEAT_END_DATE.getFieldName()), formatter).atStartOfDay() : null).build();

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				// Check if the user already have an organizer profile
				// If not, create one
				AppUser appUser = user.get();
				boolean hasBeenCreated = checkProfile(appUser);

				task.setOrganizerUser(appUser.getOrganizerUser());
				taskService.addTask(task);

				return ResponseEntity.ok(hasBeenCreated ? "Task and profile created..." : "Task created...");
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.USER_NOT_FOUND.getMessage());
			}

		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INVALID_INPUT.getMessage() + e.getMessage());
			return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	@PutMapping("/update_task")
	public ResponseEntity<?> updateTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey(ETaskControllerFields.TASK_ID.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_NAME.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_REQUIRED_ENERGY.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_START_DATE.getFieldName()) || !data.containsKey(ETaskControllerFields.TASK_END_DATE.getFieldName())) {
				return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				Task task = taskService.getTaskById(Long.parseLong(data.get(ETaskControllerFields.TASK_ID.getFieldName())));

				// Check and initialize the recurring task state if needed
				boolean isRecurrent = Boolean.parseBoolean(data.get(ETaskControllerFields.TASK_IS_RECURRENT.getFieldName()));

				if (task != null && task.getOrganizerUser().getAppUser().getUserId() == appUser.getUserId()) {
					task.setTaskName(data.get(ETaskControllerFields.TASK_NAME.getFieldName()));
					task.setTaskRequiredEnergy(Integer.parseInt(data.get(ETaskControllerFields.TASK_REQUIRED_ENERGY.getFieldName())));
					task.setTaskStartDate(LocalDateTime.parse(data.get(ETaskControllerFields.TASK_START_DATE.getFieldName())));
					task.setTaskEndDate(LocalDateTime.parse(data.get(ETaskControllerFields.TASK_END_DATE.getFieldName())));
					task.setTaskDescription(data.containsKey(ETaskControllerFields.TASK_DESCRIPTION.getFieldName()) ? data.get(ETaskControllerFields.TASK_DESCRIPTION.getFieldName()) : "Empty");
					task.setTaskPriority(taskPriorityService.getTaskPriorityByTaskPriorityName(data.get(ETaskControllerFields.TASK_PRIORITY.getFieldName())).orElse(null));

					if (!isRecurrent) {
						task.setRecurringTaskState(null); // If the task is not recurrent, set the recurring task state to null
						task.setRecurrenceEndDate(null); // Also set the recurrence end date to null
					} else {
						long repeatFrequencyID = Long.parseLong(data.get(ETaskControllerFields.TASK_REPEAT_FREQUENCY.getFieldName()));
						Optional<RecurringTaskState> recurringTaskState = recurringTaskStateService.findById(repeatFrequencyID);

						if (recurringTaskState.isPresent()) {
							RecurringTaskState state = recurringTaskState.get();
							task.setRecurringTaskState(state); // Set the new recurring task state
							task.setRecurrenceEndDate(LocalDate.parse(data.get(ETaskControllerFields.TASK_REPEAT_END_DATE.getFieldName()), formatter).atStartOfDay());
						}
					}

					if (data.containsKey(ETaskControllerFields.TASK_IS_COMPLETED.getFieldName())) {
						boolean isCompleted = Boolean.parseBoolean(data.get(ETaskControllerFields.TASK_IS_COMPLETED.getFieldName()));
						task.setTaskCompleted(isCompleted);
						task.setTaskCompletionDate(isCompleted ? LocalDateTime.now() : null);
					}
					
					taskService.updateTask(task);
					return ResponseEntity.ok().body("Task updated successfully...");
				} else {
					return ResponseEntity.badRequest().body("Task not found or does not belong to the user...");
				}
			} else {
				return ResponseEntity.badRequest().body("User not found...");
			}
		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INVALID_INPUT.getMessage() + e.getMessage());
			return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	@DeleteMapping("/delete_task")
	public ResponseEntity<?> deleteTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey(ETaskControllerFields.TASK_ID.getFieldName())) {
				return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				Task task = taskService.getTaskById(Long.parseLong(data.get(ETaskControllerFields.TASK_ID.getFieldName())));

				if (task != null && task.getOrganizerUser().getAppUser().getUserId() == appUser.getUserId()) {
					taskService.deleteTask(task);
					return ResponseEntity.ok().body("Task deleted successfully...");
				} else {
					return ResponseEntity.badRequest().body(EErrorMessages.RESOURCE_NOT_FOUND.getMessage());
				}
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.USER_NOT_FOUND.getMessage());
			}
		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INVALID_INPUT.getMessage() + e.getMessage());
			return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	@GetMapping("/get_all_tasks_recurring_states")
	public ResponseEntity<?> getAllRecurringTaskStates() {
		try {
			List<RecurringTaskState> recurringTaskStates = recurringTaskStateService.findAll();
			List<HashMap<String, String>> response = new ArrayList<>();

			for (RecurringTaskState recurringTaskState : recurringTaskStates) {
				HashMap<String, String> map = new HashMap<>();
				map.put("id", String.valueOf(recurringTaskState.getRecurringTaskStateId()));
				map.put("display_name", "Every " + (recurringTaskState.getTimeInterval() > 1 ? recurringTaskState.getTimeInterval() + " " : " ") + RecurringTaskState.RecurringTaskFrequency.fromValue(recurringTaskState.getFrequency()).getLabel());
				response.add(map);
			}

			return ResponseEntity.ok(response);
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	@PostMapping("/get_tasks_between_dates")
	public ResponseEntity<?> getTasksBetweenDates(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("start_date") || !data.containsKey("end_date")) {
				return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				List<Task> tasks = taskService.getAllTasksByUserIdAndDateRange(appUser.getOrganizerUser(), LocalDateTime.parse(data.get("start_date")), LocalDateTime.parse(data.get("end_date")));

				return ResponseEntity.ok(tasks);
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.USER_NOT_FOUND.getMessage());
			}
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	/**
	 * Check if the user already have an organizer profile if not, create one
	 * 
	 * @param appUser
	 * @throws Exception
	 */
	private boolean checkProfile(AppUser appUser) throws Exception {
		if (appUser.getOrganizerUser() == null) {
			OrganizerUser organizerUser = OrganizerUser.builder().appUser(appUser).calendarFirstShownHour(0).calendarTotalShownHours(24).build();
			appUser.setOrganizerUser(organizerUser);
			organizerUserService.create(organizerUser);
			appUserService.updateUser(appUser);
			Logger.getLogger(TaskController.class.getName()).info("Organizer profile created for user: " + appUser.getEmail());
			return true;
		}

		return false;
	}

}
