package fr.nexa.dailyorg.controller.dailyorg;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Logger;

import org.springframework.http.ResponseEntity;
import org.springframework.lang.NonNull;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import fr.nexa.dailyorg.config.JwtUtil;
import fr.nexa.dailyorg.dto.dailyorg.TaskDTO;
import fr.nexa.dailyorg.model.AppUser;
import fr.nexa.dailyorg.model.dailyorg.Category;
import fr.nexa.dailyorg.model.dailyorg.OrganizerUser;
import fr.nexa.dailyorg.model.dailyorg.RecurringTaskState;
import fr.nexa.dailyorg.model.dailyorg.Task;
import fr.nexa.dailyorg.model.dailyorg.TaskPriority;
import fr.nexa.dailyorg.service.AppUserService;
import fr.nexa.dailyorg.service.dailyorg.impl.CategoryService;
import fr.nexa.dailyorg.service.dailyorg.impl.OrganizerUserService;
import fr.nexa.dailyorg.service.dailyorg.impl.RecurringTaskStateService;
import fr.nexa.dailyorg.service.dailyorg.impl.TaskPriorityService;
import fr.nexa.dailyorg.service.dailyorg.impl.TaskService;
import fr.nexa.dailyorg.utils.EErrorMessages;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.AllArgsConstructor;

@RestController
@Validated
@RequestMapping("/api/task")
@AllArgsConstructor
public class TaskController {

	private final JwtUtil jwtUtil;

	private final TaskService taskService;
	private final RecurringTaskStateService recurringTaskStateService;
	private final AppUserService appUserService;
	private final OrganizerUserService organizerUserService;
	private final TaskPriorityService taskPriorityService;
	private final CategoryService categoryService;


	@PutMapping("/create_task")
	public ResponseEntity<?> createTask(@Valid @RequestBody TaskDTO taskDTO, BindingResult bindingResult, @NonNull HttpServletRequest request) {
		if (bindingResult.hasErrors()) {
	        return ResponseEntity.badRequest().body(bindingResult.getAllErrors());
	    }
		
		try {
			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());

			// Validate task priority if exists
			Optional<TaskPriority> taskPriority = taskPriorityService.getTaskPriorityByTaskPriorityName(taskDTO.getTaskPriority());
			if (!taskPriority.isPresent()) {
				return ResponseEntity.badRequest().body("Task priority not found...");
			}

			// Check and initialize the recurring task state if needed
			boolean isRecurrent = taskDTO.getIsRecurrent();

			Task task = Task.builder()
					.taskName(taskDTO.getTaskName())
					.ocurrenceUniqueId(UUID.randomUUID().toString())
					.taskRequiredEnergy(taskDTO.getTaskRequiredEnergy())
					.taskStartDate(taskDTO.getTaskStartDate())
					.taskEndDate(taskDTO.getTaskEndDate())
					.taskPriority(taskPriority.get())
					.taskDescription(taskDTO.getTaskDescription())
					.taskAutoGenerated(false)
					.build();

			//Check for task category
			updateCategory(task, taskDTO.getTaskCategoryId());
			
			//Check for recurring task state
			if(isRecurrent)
				if(!updateRecurringTaskState(task, taskDTO.getTaskRepeatFrequencyId(), taskDTO.getTaskRepeatEndDate())) {
					return ResponseEntity.badRequest().body(EErrorMessages.DATA_NOT_FOUND.getMessage() + " (recurring task state)");
				}
			
			
			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				// Check if the user already have an organizer profile
				// If not, create one
				AppUser appUser = user.get();
				boolean hasBeenCreated = checkProfile(appUser);

				task.setOrganizerUser(appUser.getOrganizerUser());
				taskService.addTask(task);
				return ResponseEntity.ok(hasBeenCreated ? "Task and profile created..." : "Task created...");
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.USER_NOT_FOUND.getMessage());
			}
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	@PutMapping("/update_task")
	public ResponseEntity<?> updateTask(@Valid @RequestBody TaskDTO taskDTO, BindingResult bindingResult,  @NonNull HttpServletRequest request) {
		if (bindingResult.hasErrors()) {
	        return ResponseEntity.badRequest().body(bindingResult.getAllErrors());
	    }
		
		try {
			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());

			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				Task task = taskService.getTaskById(taskDTO.getTaskId());

				// Check and initialize the recurring task state if needed
				boolean isRecurrent = taskDTO.getIsRecurrent();

				if (task != null && task.getOrganizerUser().getAppUser().getUserId() == appUser.getUserId()) {
					//Check for task category
					task.setCategory(null);
					updateCategory(task, taskDTO.getTaskCategoryId());
					
					task.setTaskName(taskDTO.getTaskName());
					task.setTaskRequiredEnergy(taskDTO.getTaskRequiredEnergy());
					task.setTaskStartDate(taskDTO.getTaskStartDate());
					task.setTaskEndDate(taskDTO.getTaskEndDate());
					task.setTaskDescription(taskDTO.getTaskDescription());
					
					updatePriorityFromPriorityName(task, taskDTO.getTaskPriority());
					
					if (!isRecurrent) {
						task.setRecurringTaskState(null); // If the task is not recurrent, set the recurring task state to null
						task.setRecurrenceEndDate(null); // Also set the recurrence end date to null
					} else {
						updateRecurringTaskState(task, taskDTO.getTaskRepeatFrequencyId(), taskDTO.getTaskRepeatEndDate());
					}
					
					task.setTaskCompleted(taskDTO.getIsTaskCompleted());
					task.setTaskCompletionDate(taskDTO.getIsTaskCompleted() ? LocalDateTime.now() : null);

					taskService.updateTask(task);
					return ResponseEntity.ok().body("Task updated successfully...");
				} else {
					return ResponseEntity.badRequest().body("Task not found or does not belong to the user...");
				}
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.USER_NOT_FOUND.getMessage());
			}
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
		
	}

	@DeleteMapping("/delete_task")
	public ResponseEntity<?> deleteTask(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey(ETaskControllerFields.TASK_ID.getFieldName())) {
				return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			AppUser appUser = user.get();
			Task task = taskService.getTaskById(Long.parseLong(data.get(ETaskControllerFields.TASK_ID.getFieldName())));

			if (task != null && task.getOrganizerUser().getAppUser().getUserId() == appUser.getUserId()) {
				taskService.deleteTask(task);
				return ResponseEntity.ok().body("Task deleted successfully...");
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.RESOURCE_NOT_FOUND.getMessage());
			}
		} catch (NumberFormatException e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INVALID_INPUT.getMessage() + e.getMessage());
			return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	@GetMapping("/get_all_tasks_recurring_states")
	public ResponseEntity<?> getAllRecurringTaskStates() {
		List<RecurringTaskState> recurringTaskStates = recurringTaskStateService.findAll();
		List<HashMap<String, String>> response = new ArrayList<>();

		for (RecurringTaskState recurringTaskState : recurringTaskStates) {
			HashMap<String, String> map = new HashMap<>();
			map.put("id", String.valueOf(recurringTaskState.getRecurringTaskStateId()));
			map.put("display_name", "Every " + (recurringTaskState.getTimeInterval() > 1 ? recurringTaskState.getTimeInterval() + " " : "") + RecurringTaskState.RecurringTaskFrequency.fromValue(recurringTaskState.getFrequency()).getLabel());
			response.add(map);
		}

		return ResponseEntity.ok(response);
	}

	@PostMapping("/get_tasks_between_dates")
	public ResponseEntity<?> getTasksBetweenDates(@RequestBody Map<String, String> data, @NonNull HttpServletRequest request) {
		try {
			if (!data.containsKey("start_date") || !data.containsKey("end_date")) {
				return ResponseEntity.badRequest().body(EErrorMessages.INVALID_INPUT.getMessage());
			}

			String userEmail = jwtUtil.extractUsernameFromCookies(request.getCookies());
			Optional<AppUser> user = appUserService.findByEmail(userEmail);

			if (user.isPresent()) {
				AppUser appUser = user.get();
				
				// Ensure the user has an organizer profile
				checkProfile(appUser);
				
				List<Task> tasks = taskService.getAllTasksByUserIdAndDateRange(appUser.getOrganizerUser(), LocalDateTime.parse(data.get("start_date")), LocalDateTime.parse(data.get("end_date")));

				return ResponseEntity.ok(tasks);
			} else {
				return ResponseEntity.badRequest().body(EErrorMessages.USER_NOT_FOUND.getMessage());
			}
		} catch (Exception e) {
			Logger.getLogger(TaskController.class.getName()).severe(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage() + e.getMessage());
			return ResponseEntity.internalServerError().body(EErrorMessages.INTERNAL_SERVER_ERROR.getMessage());
		}
	}

	/**
	 * Check if the user already have an organizer profile if not, create one
	 * 
	 * @param appUser
	 * @throws Exception
	 */
	private boolean checkProfile(AppUser appUser) throws Exception {
		if (appUser.getOrganizerUser() == null) {
			OrganizerUser organizerUser = OrganizerUser.builder().appUser(appUser).calendarFirstShownHour(0).calendarTotalShownHours(24).build();
			appUser.setOrganizerUser(organizerUser);
			organizerUserService.update(organizerUser);
			appUserService.updateUser(appUser);
			Logger.getLogger(TaskController.class.getName()).info("Organizer profile created for user: " + appUser.getEmail());
			return true;
		}

		return false;
	}
	
	/**
	 * Update the category of a task if the categoryId is not null and the category
	 * exists
	 * 
	 * @param task
	 * @param categoryId
	 * @return
	 * @throws Exception
	 */
	private boolean updateCategory(Task task, Long categoryId) throws Exception {
		if (categoryId != null) {
			Category category = categoryService.findById(categoryId);
			if(category != null) {
				task.setCategory(category);
				return true;
			}
		}
		return false;
	}
	
	/**
	 * Update the recurring task state of a task if the recurringTaskStateId is not
	 * null and the recurring task state exists
	 * 
	 * @param task
	 * @param recurringTaskStateId
	 * @param recurringTaskEndDate
	 * @return
	 * @throws Exception
	 */
	private boolean updateRecurringTaskState(Task task, Long recurringTaskStateId, LocalDate recurringTaskEndDate) throws Exception {
		if (recurringTaskStateId != null) {
			Optional<RecurringTaskState> recurringTaskState = recurringTaskStateService.findById(recurringTaskStateId);
			if(recurringTaskState.isPresent()) {
				task.setRecurringTaskState(recurringTaskState.get());
				task.setRecurrenceEndDate(recurringTaskEndDate.atStartOfDay());
				return true;
			}
		}
		return false;
	}
	
	/**
	 * Update the priority of a task if the priorityName is not null and the
	 * priority exists
	 * 
	 * @param task
	 * @param priorityName
	 * @return
	 * @throws Exception
	 */
	private boolean updatePriorityFromPriorityName(Task task, String priorityName) throws Exception {
		if (priorityName != null) {
			Optional<TaskPriority> taskPriority = taskPriorityService.getTaskPriorityByTaskPriorityName(priorityName);
			if(taskPriority.isPresent()) {
				task.setTaskPriority(taskPriority.get());
				return true;
			}
		}
		return false;
	}
}
