package fr.nexa.dailyorg.components.factory.dailyorg;

import java.time.LocalDateTime;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.github.javafaker.Faker;

import fr.nexa.dailyorg.model.dailyorg.OrganizerUser;
import fr.nexa.dailyorg.model.dailyorg.Task;
import fr.nexa.dailyorg.model.dailyorg.TaskPriority;
import fr.nexa.dailyorg.repository.dailyorg.ITaskRepository;
import lombok.AllArgsConstructor;

@Component
@AllArgsConstructor(onConstructor = @__({@Autowired}))
public class TaskFactory {
	
	private final Faker faker = Faker.instance();
	
	private final ITaskRepository taskRepository;
	
	private final OrganizerUserFactory organizerUserFactory;
	private final TaskPriorityFactory taskPriorityFactory;
	private final RecurringTaskStateFactory recurringTaskStateFactory;

	public Task createOneTask() {
		OrganizerUser organizerUser = organizerUserFactory.createAndInsertOneOrganizerUser();
		TaskPriority taskPriority = taskPriorityFactory.createAndInsertOneTaskPriority();
		
		return Task.builder()
				.taskName(faker.lorem().word())
				.taskDescription(faker.lorem().sentence())
				.taskRequiredEnergy((int) (Math.random() * 10))
				.taskStartDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(8))
				.taskEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(9))
				.isTaskCompleted(false)
				.taskAutoGenerated(false)
				.ocurrenceUniqueId(UUID.randomUUID().toString())
				.recurrenceEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusDays(30))
				.organizerUser(organizerUser)
				.taskPriority(taskPriority)
				.build();
	}
	
	public Task createAndInsertOneTask() {
		Task task = createOneTask();
		return taskRepository.save(task);
	}
	
	public Task createAndInsertOneTaskWithRecurringTaskState() {
		Task task = createOneTask();
		task.setRecurringTaskState(recurringTaskStateFactory.createAndInsertOneRecurringTaskState());
		return taskRepository.save(task);
	}
}
