package fr.nexa.dailyorg.components.factory.dailyorg;

import java.time.LocalDateTime;
import java.util.Random;
import java.util.UUID;

import com.github.javafaker.Faker;

import fr.nexa.dailyorg.components.factory.AppUserFactory;
import fr.nexa.dailyorg.model.dailyorg.Task;

public class TaskFactory {
	
	private final Faker faker = Faker.instance();
	private final Random random = new Random();
	
	public Task createOneTask() {
		return Task.builder()
				.taskName(faker.lorem().word())
				.taskDescription(faker.lorem().sentence())
				.taskRequiredEnergy(random.nextInt(11))
				.taskStartDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(8))
				.taskEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(9))
				.isTaskCompleted(false)
				.taskAutoGenerated(false)
				.ocurrenceUniqueId(UUID.randomUUID().toString())
				.recurrenceEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusDays(30))
				.build();
	}
	
	public Task createOneTaskWithOrganizerUserAndTaskPriority(OrganizerUserFactory organizerUserFactory, AppUserFactory appUserFactory,TaskPriorityFactory taskPriorityFactory) {
		return Task.builder()
				.taskName(faker.lorem().word())
				.taskDescription(faker.lorem().sentence())
				.taskRequiredEnergy(random.nextInt(11))
				.taskStartDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(8))
				.taskEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(9))
				.isTaskCompleted(false)
				.taskAutoGenerated(false)
				.ocurrenceUniqueId(UUID.randomUUID().toString())
				.recurrenceEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusDays(30))
				.organizerUser(organizerUserFactory.createOneOrganizerUser(appUserFactory.createOneAppUser()))
				.taskPriority(taskPriorityFactory.createOneTaskPriority())
				.build();
	}
	
	public Task createOneTaskWithTaskPriority(TaskPriorityFactory taskPriorityFactory) {
		return Task.builder()
				.taskName(faker.lorem().word())
				.taskDescription(faker.lorem().sentence())
				.taskRequiredEnergy(random.nextInt(11))
				.taskStartDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(8))
				.taskEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(9))
				.isTaskCompleted(false)
				.taskAutoGenerated(false)
				.ocurrenceUniqueId(UUID.randomUUID().toString())
				.recurrenceEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusDays(30))
				.taskPriority(taskPriorityFactory.createOneTaskPriority())
				.build();
	}
}
