package fr.nexa.dailyorg.components.factory.dailyorg;

import java.time.LocalDateTime;
import java.util.UUID;

import com.github.javafaker.Faker;

import fr.nexa.dailyorg.model.dailyorg.Task;

public class TaskFactory {
	
	private final Faker faker = Faker.instance();
	
	public Task createOneTask() {
		return Task.builder()
				.taskName(faker.lorem().word())
				.taskDescription(faker.lorem().sentence())
				.taskRequiredEnergy((int) (Math.random() * 10))
				.taskStartDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(8))
				.taskEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusHours(9))
				.isTaskCompleted(false)
				.taskAutoGenerated(false)
				.ocurrenceUniqueId(UUID.randomUUID().toString())
				.recurrenceEndDate(LocalDateTime.now().toLocalDate().atStartOfDay().plusDays(30))
				.build();
	}
}
